name: Edit outside.list

on:
  push:
    branches: [ master ]

jobs:
  edit_file:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Acquire outside.list
        run: curl -o outside.list https://fastly.jsdelivr.net/gh/GeQ1an/Rules@master/QuantumultX/Filter/Outside.list
      - name: Edit outside.list
        run: |
          grep -iv "duolingo" outside.list > outside_edt.list
          mv outside_edt.list QuantumultX/outside_edt.list
