name: Edit outside.list

on:
  schedule:
    - cron:  '0 */8 * * *'
  workflow_dispatch:

jobs:
  edit_file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set identity
        run: |
          git config --global user.email "sky31even@gmail.com"
          git config --global user.name "sky31even"
      - name: Acquire outside_QuantumultX.list
        run: curl -o outside_QuantumultX.list https://fastly.jsdelivr.net/gh/GeQ1an/Rules@master/QuantumultX/Filter/Outside.list
      - name: Edit outside_QuantumultX.list
        run: |
          grep -iv "duolingo" outside_QuantumultX.list --in-place
      - name: Save changes
        run: |
          git add .
          git commit -m "Update the outside filter on: $(TZ=UTC+8 date +%Y-%m-%d %T)"
          git push
